import { NextRequest, NextResponse } from "next/server";
import { getSupabaseClient } from "@/lib/supabase";
import { getAuthUser, unauthorizedResponse } from "@/lib/auth";
import { generateMemoContent } from "@/lib/generateMemoContent";
import type { ApiError } from "@/lib/types";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
} from "docx";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function errorJson(error: string, detail: string | undefined, status: number) {
  return NextResponse.json({ error, detail } satisfies ApiError, { status });
}

function buildSectionBody(content: string): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  for (const line of content.split("\n")) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    if (trimmed.startsWith("- ")) {
      paragraphs.push(
        new Paragraph({
          text: trimmed.slice(2),
          bullet: { level: 0 },
        })
      );
    } else if (trimmed.startsWith("**") && trimmed.endsWith("**")) {
      paragraphs.push(
        new Paragraph({
          children: [
            new TextRun({ text: trimmed.slice(2, -2), bold: true }),
          ],
          spacing: { before: 100 },
        })
      );
    } else {
      // Regular paragraph — handle inline **bold** spans
      const parts = trimmed.split(/(\*\*[^*]+\*\*)/);
      paragraphs.push(
        new Paragraph({
          children: parts.map((p) => {
            if (p.startsWith("**") && p.endsWith("**")) {
              return new TextRun({ text: p.slice(2, -2), bold: true });
            }
            return new TextRun({ text: p });
          }),
          spacing: { before: 80 },
        })
      );
    }
  }
  return paragraphs;
}

/**
 * POST /api/export/memo?ticker=TICKER — generates and returns a .docx research memo
 */
export async function POST(req: NextRequest) {
  const user = await getAuthUser(req);
  if (!user) return unauthorizedResponse();

  const ticker = new URL(req.url).searchParams
    .get("ticker")
    ?.trim()
    .toUpperCase();
  if (!ticker || ticker.length > 10) {
    return errorJson("Missing or invalid 'ticker' query param", undefined, 400);
  }

  const supabase = getSupabaseClient();

  // Look up company name
  const { data: co } = await supabase
    .from("companies")
    .select("name")
    .ilike("ticker", ticker)
    .maybeSingle() as { data: { name: string } | null; error: unknown };

  if (!co) {
    return errorJson("Company not found", `No company with ticker '${ticker}'`, 404);
  }

  const companyName = co.name;

  let sections;
  try {
    sections = await generateMemoContent(ticker, companyName);
  } catch (e) {
    return errorJson(
      "Failed to generate memo content",
      e instanceof Error ? e.message : "Unknown error",
      502
    );
  }

  const dateStr = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          // Cover
          new Paragraph({
            children: [
              new TextRun({
                text: `${companyName} (${ticker})`,
                bold: true,
                size: 40,
              }),
            ],
            heading: HeadingLevel.TITLE,
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "Equity Research Memo · Investment Seeker AI",
                color: "666666",
                size: 22,
              }),
            ],
            spacing: { after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: `Generated: ${dateStr}`,
                color: "888888",
                size: 18,
              }),
            ],
            spacing: { after: 400 },
          }),

          // Sections
          ...sections.flatMap((section) => [
            new Paragraph({
              text: section.title,
              heading: HeadingLevel.HEADING_1,
              spacing: { before: 400, after: 120 },
            }),
            ...buildSectionBody(section.content),
          ]),

          // Disclaimer
          new Paragraph({
            children: [
              new TextRun({
                text: "DISCLAIMER: Generated by Investment Seeker AI for internal research purposes only. Does not constitute investment advice. Conduct independent due diligence before acting.",
                color: "888888",
                size: 16,
                italics: true,
              }),
            ],
            spacing: { before: 600 },
          }),
        ],
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  const arrayBuffer = buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength) as ArrayBuffer;

  const filename = `${ticker}_research_memo_${new Date().toISOString().slice(0, 10)}.docx`;
  return new Response(arrayBuffer, {
    status: 200,
    headers: {
      "Content-Type":
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(buffer.byteLength),
    },
  });
}
